apiVersion : v1
kind : ConfigMap
metadata:
  name : db-config
data:
  host : postgresql
  dbName: EV_database
  postgresql-initdb: |
    set -e
    sudo apt install -y wget ca-certificates
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
    sudo apt update
    sudo apt install -y postgresql postgresql-contrib
    service postgresql status
    sudo -u postgres psql -c "CREATE USER renault_admin WITH ENCRYPTED PASSWORD 'wellop';"
    sudo -u postgres psql -c "CREATE DATABASE \"EV_database\";"
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE \"EV_database\" TO renault_admin;"

 