apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  #namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: alertmanager
  #type: NodePort  
  ports:
    - port: 9095
      targetPort: 9095
      #nodePort: 31000